# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /export/home/fils/stud/g/grigore.lupescu/ethereum-wp/ethash

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /export/home/fils/stud/g/grigore.lupescu/ethereum-wp/ethash

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /export/home/fils/stud/g/grigore.lupescu/ethereum-wp/ethash && $(CMAKE_COMMAND) -E cmake_progress_start /export/home/fils/stud/g/grigore.lupescu/ethereum-wp/ethash/CMakeFiles /export/home/fils/stud/g/grigore.lupescu/ethereum-wp/ethash/src/libethash-cl/CMakeFiles/progress.marks
	cd /export/home/fils/stud/g/grigore.lupescu/ethereum-wp/ethash && $(MAKE) -f CMakeFiles/Makefile2 src/libethash-cl/all
	$(CMAKE_COMMAND) -E cmake_progress_start /export/home/fils/stud/g/grigore.lupescu/ethereum-wp/ethash/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /export/home/fils/stud/g/grigore.lupescu/ethereum-wp/ethash && $(MAKE) -f CMakeFiles/Makefile2 src/libethash-cl/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /export/home/fils/stud/g/grigore.lupescu/ethereum-wp/ethash && $(MAKE) -f CMakeFiles/Makefile2 src/libethash-cl/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /export/home/fils/stud/g/grigore.lupescu/ethereum-wp/ethash && $(MAKE) -f CMakeFiles/Makefile2 src/libethash-cl/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /export/home/fils/stud/g/grigore.lupescu/ethereum-wp/ethash && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
src/libethash-cl/CMakeFiles/ethash-cl.dir/rule:
	cd /export/home/fils/stud/g/grigore.lupescu/ethereum-wp/ethash && $(MAKE) -f CMakeFiles/Makefile2 src/libethash-cl/CMakeFiles/ethash-cl.dir/rule
.PHONY : src/libethash-cl/CMakeFiles/ethash-cl.dir/rule

# Convenience name for target.
ethash-cl: src/libethash-cl/CMakeFiles/ethash-cl.dir/rule
.PHONY : ethash-cl

# fast build rule for target.
ethash-cl/fast:
	cd /export/home/fils/stud/g/grigore.lupescu/ethereum-wp/ethash && $(MAKE) -f src/libethash-cl/CMakeFiles/ethash-cl.dir/build.make src/libethash-cl/CMakeFiles/ethash-cl.dir/build
.PHONY : ethash-cl/fast

ethash_cl_miner.o: ethash_cl_miner.cpp.o
.PHONY : ethash_cl_miner.o

# target to build an object file
ethash_cl_miner.cpp.o:
	cd /export/home/fils/stud/g/grigore.lupescu/ethereum-wp/ethash && $(MAKE) -f src/libethash-cl/CMakeFiles/ethash-cl.dir/build.make src/libethash-cl/CMakeFiles/ethash-cl.dir/ethash_cl_miner.cpp.o
.PHONY : ethash_cl_miner.cpp.o

ethash_cl_miner.i: ethash_cl_miner.cpp.i
.PHONY : ethash_cl_miner.i

# target to preprocess a source file
ethash_cl_miner.cpp.i:
	cd /export/home/fils/stud/g/grigore.lupescu/ethereum-wp/ethash && $(MAKE) -f src/libethash-cl/CMakeFiles/ethash-cl.dir/build.make src/libethash-cl/CMakeFiles/ethash-cl.dir/ethash_cl_miner.cpp.i
.PHONY : ethash_cl_miner.cpp.i

ethash_cl_miner.s: ethash_cl_miner.cpp.s
.PHONY : ethash_cl_miner.s

# target to generate assembly for a file
ethash_cl_miner.cpp.s:
	cd /export/home/fils/stud/g/grigore.lupescu/ethereum-wp/ethash && $(MAKE) -f src/libethash-cl/CMakeFiles/ethash-cl.dir/build.make src/libethash-cl/CMakeFiles/ethash-cl.dir/ethash_cl_miner.cpp.s
.PHONY : ethash_cl_miner.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... ethash-cl"
	@echo "... rebuild_cache"
	@echo "... ethash_cl_miner.o"
	@echo "... ethash_cl_miner.i"
	@echo "... ethash_cl_miner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /export/home/fils/stud/g/grigore.lupescu/ethereum-wp/ethash && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

